# .woodpecker.yml
# Auto-deploy personal-website on same VPS
when:
  event: [ push, manual ]
  branch: [ main ]

steps:
  deploy:
    image: alpine:3.20
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      PROJECT_PATH: /srv/personal-website
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ego/app/personal-website:/srv/personal-website
    commands:
      - echo "Deploying personal-website on indraswara.me"
      - apk add --no-cache git docker-cli
      - cd "$PROJECT_PATH"
      - git pull origin main
      - docker compose pull
      - docker compose up -d --remove-orphans
      - docker system prune -f
