# .woodpecker.yml

when:
  event: [ push, manual ]
  branch: [ main ]

steps:
  deploy:
    image: alpine:3.20
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      PROJECT_PATH: /srv/personal-website
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ego/app/personal-website:/srv/personal-website
    commands:
      - echo "Deploying personal-website on indraswara.me"
      - apk add --no-cache git docker-cli docker-compose
      - cd "$PROJECT_PATH"
      - git config --global --add safe.directory /srv/personal-website
      - git reset --hard HEAD
      - git clean -fd
      - git pull origin main
      - docker-compose down -v
      - docker-compose -f docker-compose.prod.yml up -d --build
