# Woodpecker CI/CD for writeups.indraswara.me
# Simple, working configuration with git pull and docker compose deploy

clone:
  depth: 1

steps:
  deploy:
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: main
      event:
        - push
        - manual
    commands:
      - if [ -d ".git" ]; then git fetch origin main && git reset --hard origin/main; else rm -rf ./* && git clone --depth=1 -b main https://github.com/Indraswara/writeups.git .; fi
      - docker compose -f docker-compose.yml pull || true
      - docker compose -f docker-compose.yml up -d --build --remove-orphans
      - docker system prune -f

  healthcheck:
    image: alpine/curl
    depends_on:
      - deploy
    when:
      branch: main
      event:
        - push
        - manual
    commands:
      - curl -sSf https://writeups.indraswara.me > /dev/null

  cleanup:
    image: alpine
    when:
      event:
        - manual
    commands:
      - docker system prune -af
      - docker volume prune -f
      - docker network prune -f
