# .woodpecker.yml
when:
  event: [ push, manual ]
  branch: main

steps:
  deploy:
    image: alpine:3.20
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      PROJECT_PATH: /srv/personal-website
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/websites/personal-website:/opt/websites/personal-website
    commands:
      - echo "Deploying personal-website on indraswara.me"
      - apk add --no-cache git docker-cli docker-cli-compose
      - cd /home/ego/app/websites/personal-website
      - git config --global --add safe.directory /opt/websites/personal-website
      - git fetch --all
      - git reset --hard origin/main
      - docker compose -f prod.yml up -d --build
