# .woodpecker.yml
when:
  event: [ push, manual ]
  branch: main

steps:
  deploy:
    image: alpine:3.20
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      PROJECT_PATH: /srv/personal-website
    volumes:
      - /home/ego/app/websites/personal-website:/home/ego/app/websites/personal-website
    commands:
      - echo "Deploying personal-website on indraswara.me"
      - apk add --no-cache git
      - cd /home/ego/app/websites/personal-website
      - git config --global --add safe.directory /home/ego/app/websites/personal-website
      - git fetch --all
      - git reset --hard origin/main
      - docker compose up -d --build